### ISSUE TITLE
Update "Delegations Handbook"

### ISSUE THREAD

**Issue by nullmames** [CosmosContracts/docs#42]
Update delegations handbook with new dates, any other changes required.

**Comment by poroburu** [comment]
Could the delegation wallet address be included? Would like to know current active delegations.

**Comment by nullmames** [comment]
this section will be removed soon. Delegations will be managed by the Delegations SubDAO

**Comment by poroburu** [comment]
Where is the address? Where can I find it starting from https://www.junonetwork.io/ecosystem ?

**Comment by nullmames** [comment]
It is actually the dev fund

`https://www.mintscan.io/juno/account/juno190g5j8aszqhvtg7cprmev8xcxs6csra7xnk3n3`
