### ISSUE TITLE
Replace ERC-20 page with CW-20

### ISSUE THREAD

**Issue by Callum-A** [CosmosContracts/docs#50]

**Comment by nullmames** [comment]
Hi @Callum-A 

Are you proposing to make the change? Or just flagging it?

**Comment by Callum-A** [comment]
> Hi @Callum-A 
> 
> 
> 
> Are you proposing to make the change? Or just flagging it?

I plan to get round to it, flagging it here so I don't forget 😅

**Comment by Reecepbcups** [comment]
completed
